//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApptest11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayttajat
    {
        public int KayttajaID { get; set; }
        public string Kayttajatunnus { get; set; }
        public string Salasana { get; set; }
    }
}
